### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by assemmarwan** [lessthanoptimal/RobotWebcamVO#1]
Some lines of code the arguments passed are incorrect and the classes used in loading XML are wrong.
Line 57: instead of passing target, target.points should be passed.
Line 146 and 158: The class UtilIO should be used instead of BoofMiscOps.

Thanks in advance!

**Comment by lessthanoptimal** [comment]
yeah it's probably a bit out of date.  Hopefully I'll have a chance to update it.  if you figure it out could you post a pull request?
